### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bip1tairy** [ynshung/blender-colab#10]
When downloading a file directly from a PC, a bin bash error is generated, which says that the file or directory is missing, this did not happen before, the files are not corrupted, I even changed the blender version to the newest one (was 3.0.1)

![Screenshot_2](https://user-images.githubusercontent.com/111730395/185858429-8044bd7f-57db-45fa-9e71-d835a3621270.png)

![Screenshot_1](https://user-images.githubusercontent.com/111730395/185858439-23517fbc-d01d-43ae-8dee-5882f120965b.png)

**Comment by ynshung** [comment]
Thank you @bip1tairy for the report! Let me know if there's any new problem.
