### ISSUE TITLE
Error in blender_url = blender_url_dict[blender_version]

### ISSUE THREAD

**Issue by Makasin22** [ynshung/blender-colab#3]
Error:
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-d60300aed110> in <module>()
      9                     '2.93.1'  : "https://ftp.nluug.nl/pub/graphics/blender/release/Blender2.93/blender-2.93.4-linux-x64.tar.xz"}
     10 
---> 11 blender_url = blender_url_dict[blender_version]
     12 base_url = os.path.basename(blender_url)
     13 

KeyError: '2.93.4'`

Setup:
![image](https://user-images.githubusercontent.com/60397552/134188031-e9f1d4fe-7568-4157-9071-566899a4049c.png)

**UPD**. No error occurs if i choose version 2.92.0

**Comment by ynshung** [comment]
Thank you for your report!
