### ISSUE TITLE
Reduce render samples?

### ISSUE THREAD

**Issue by rgbaman** [ynshung/blender-colab#4]
Great little tool, thank you!

When rendering it defaults to 510 tiles, when I want to sample only 64. Is that possible?

**Comment by ynshung** [comment]
Hello rgbaman, thank you for the kind comments! You can change the samples in the blender file and reupload it, or you can add the following code (the line with `scene.cycles.sample`) at the cell which enables GPU rendering. Example:

    "print(cprefs)\n"+\
    "scene.cycles.samples = 64\n"+\
    "for compute_device_type in ('CUDA', 'OPENCL', 'NONE'):\n"+\
    (other code)
