### ISSUE TITLE
Rendering not working

### ISSUE THREAD

**Issue by tylee04** [ynshung/blender-colab#5]
I was able to upload my own video
However, an error message was output from the third code paragraph, "rm: cannot remove 'render': No such file or directory"
But I ignored it and executed the 9th code, and Blender 3.0 was installed well.
I thought it went well because the fifth paragraph didn't print anything out.
The 6th paragraph was filled with error codes below.
What is wrong with this?
first what is the error "rm: cannot remove 'render': No such file or directory"
and what should i do?

Blender 3.0.0 (hash f1cca3055776 built 2021-12-03 00:34:54)
Read blend: /content/render/Nubula.blend
<bpy_struct, CyclesPreferences at 0x7fe99b1a7068>
Device found: CUDA
Activating <bpy_struct, CyclesDeviceSettings("Tesla K80") at 0x7fe9995f5f88>
Failed to create CUDA context (Unknown error)

Refer to the Cycles GPU rendering documentation for possible solutions:
https://docs.blender.org/manual/en/latest/render/cycles/gpu_rendering.html

Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
Invalid context in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (intern/cycles/device/cuda/queue.cpp:33)
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Fra:1 Mem:16.37M (Peak 16.42M) | Time:00:00.14 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Synchronizing object | Nebula
Fra:1 Mem:16.37M (Peak 16.42M) | Time:00:00.14 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Synchronizing object | Suzanne
Fra:1 Mem:16.42M (Peak 16.43M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Synchronizing object | Cube
Fra:1 Mem:16.48M (Peak 16.48M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Initializing
Fra:1 Mem:16.48M (Peak 16.48M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Waiting for render to start
Fra:1 Mem:16.48M (Peak 16.48M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Loading render kernels (may take a few minutes the first time)
Fra:1 Mem:16.48M (Peak 16.48M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Failed to create CUDA context (Unknown error)
Error: Failed to create CUDA context (Unknown error)
Fra:1 Mem:16.48M (Peak 16.48M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Updating Scene
Fra:1 Mem:16.48M (Peak 16.48M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Updating Shaders
Fra:1 Mem:16.48M (Peak 16.48M) | Time:00:00.15 | Mem:0.00M, Peak:0.00M | Scene, ViewLayer | Loading denoising kernels (may take a few minutes the first time)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
System is out of GPU and shared host memory
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Fra:1 Mem:20.49M (Peak 20.49M) | Time:00:00.18 | Mem:338.00M, Peak:338.00M | Scene, ViewLayer | Failed to create CUDA context (Unknown error)
Invalid value in cuCtxPushCurrent(device->cuContext) (intern/cycles/device/cuda/util.cpp:26)
Invalid context in cuCtxPopCurrent(NULL) (intern/cycles/device/cuda/util.cpp:31)
Invalid value in cuCtxDestroy_v2(cuContext) (intern/cycles/device/cuda/device_impl.cpp:144)

Blender quit

**Comment by dev-kasibhatla** [comment]
What was the workaround? @tylee04

**Comment by ynshung** [comment]
Hi @dev-kasibhatla, the code now includes fixes for this particular problem. Let me know if there's any additional issue. Cheers!

**Comment by dev-kasibhatla** [comment]
Many thanks for the prompt fix!  It works now @ynshung
